name: fus_world
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  splashscreen: ^1.2.0
  carousel_slider: ^2.2.1
  flutter_rating_bar: ^3.0.1+1
  flutter_slidable: ^0.5.5
  firebase_core: ^0.4.0+9
  cloud_firestore:
  firebase_auth: ^0.16.1
  intl:
  group_radio_button: ^1.0.1
  shared_preferences: ^0.5.8
  #code_input:
  pin_code_fields: ^6.0.0
  flutter_screenutil: ^2.3.1
  flutter_svg: any
  firebase_storage: ^3.1.6
  simple_animations:
  flutter_open_whatsapp:
  flushbar: ^1.10.4
  photo_view: ^0.10.2








dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Mulish
      fonts:
        - asset: fonts/Mulish-Regular.ttf
        - asset: fonts/Mulish-Bold.ttf
        - asset: fonts/Kufi.ttf
          style: italic

    - family: Kufi
      fonts:
        - asset: fonts/Kufi.ttf

  assets:
    - assets/logo.jpg
    - assets/en.json
    - assets/ar.json
    - assets/login.svg
    - assets/success.svg



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
